stages:
  - validate
  - test

default:
  image: node:20-alpine
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

variables:
  NPM_CONFIG_CACHE: .npm

include:
  - component: ${CI_SERVER_HOST}/components/ai-catalog/catalog-sync@0.0.1
    inputs:
      enable_in_project: 'false'
      auto_release: 'false'

test:
  stage: test
  script:
    - npm install
    - npm run build
    - npm test
